 
// hash_check.sol
// TODO: This file is auto-generated by SnarkJS to enable zk proof verification in Solidity.
// It is mainly useful for EVM-based test environments or interoperability testing.
//
// ✅ How to Generate:
// Run the following after generating your zkey:
//
//   snarkjs zkey export solidityverifier ../../artifacts/hash_check/hash_check.zkey hash_check.sol
//
// 🔒 This file verifies Groth16 proofs off-chain or on-chain in EVM networks.
//
// NOTE:
// - This file is **not used in Solana-based backend**, but retained for tooling/test coverage.
// - DO NOT edit manually unless writing a custom verifier.
